resource_group_name = "prod-resource-group"
location            = "West Europe"
vnet_name           = "prod-vnet"
address_space       = ["10.0.0.0/16"]
subnet_name         = "prod-subnet"
subnet_prefixes     = ["10.0.2.0/24"]
vm_name             = "prod-webserver"
admin_username      = "prodadmin"
admin_password      = "ProdPassword123!"
